- readme.md
Added link to my GitHub repo on readMe.md
> Added GitHub link on readMe

- readme.md
- routes/index.js
- views/index.ejs
- views/partials/footer.ejs
- views/partials/header.ejs
> fixed header/footer in views

- config/passport.js
- views/_partials/footer.ejs
- views/_partials/header.ejs
- views/index.ejs
> fixed header/footer/login

- controllers/moviesController.js
- controllers/usersController.js
- routes/movies.js
- server.js
- views/movies/index.ejs
> add Controllers

- .env
- controllers/movies.js
- controllers/moviesController.js
- package-lock.json
- package.json
- routes/index.js
- routes/movies.js
- views/movies/index.ejs
> Hit API for movies

- controllers/moviesController.js
- public/js/main.js
- public/stylesheets/style.css
- views/_partials/header.ejs
- views/movies/index.ejs
super cool styling for movies index
> style movie index

- public/stylesheets/style.css
- views/_partials/footer.ejs
- views/_partials/header.ejs
- views/movies/index.ejs
> style carousel

- public/stylesheets/style.css
- views/movies/index.ejs
> img adjusted carousel

- controllers/moviesController.js
- models/user.js
- views/_partials/footer.ejs
- views/movies/index.ejs
- views/movies/show.ejs
> vie page started and other tons o shit

- .env
- controllers/moviesController.js
- package-lock.json
- package.json
- routes/movies.js
- server.js
- views/movies/show.ejs
> fixed movie view page

- controllers/moviesController.js
- controllers/usersController.js
- routes/users.js
- views/_partials/header.ejs
- views/users/show.ejs
Fixed the favorites function so more than one user can favorite, and a user can only favorite a movie once.
> fix favorite function

- controllers/usersController.js
- views/users/show.ejs
populate favorites on user show page
> populate favorites on user show page

- controllers/moviesController.js
- package-lock.json
- package.json
- public/js/main.js
- routes/movies.js
- routes/users.js
- server.js
- views/_partials/header.ejs
- views/users/show.ejs
> Super cool delete feature

- views/users/show.ejs
> add content to favorites

- views/users/show.ejs
> adjusted delete feature

- controllers/moviesController.js
> fixed commenting issue

- controllers/moviesController.js
- routes/movies.js
- views/_partials/header.ejs
- views/movies/results.ejs
> Add search functionality

- readme.md
> readme round 1

- controllers/moviesController.js
> fixed favorites route

- public/stylesheets/style.css
- views/_partials/header.ejs
- views/movies/index.ejs
- views/movies/results.ejs
- views/movies/show.ejs
- views/users/show.ejs
> styling of both show pages and functionality

- controllers/moviesController.js
- models/movie.js
- views/_partials/header.ejs
- views/movies/show.ejs
> fixed user commenting

- public/stylesheets/style.css
- views/_partials/header.ejs
> fixed some css stuff

- controllers/moviesController.js
- controllers/usersController.js
- public/stylesheets/style.css
- views/_partials/header.ejs
- views/movies/index.ejs
- views/movies/show.ejs
- views/users/show.ejs
half of the movie show page renders with API, the comments part renders with our db ._id.
Comments are persisted and displayed.
Made carousel clickable show page links.
> fix comments, fix movie show page/models

- public/stylesheets/style.css
- views/_partials/header.ejs
- views/movies/show.ejs
- views/users/show.ejs
> CSS styling

- controllers/moviesController.js
- controllers/usersController.js
- routes/movies.js
- views/movies/index.ejs
- views/movies/results.ejs
- views/movies/show.ejs
Comments on the show page now display the user who commented and their information.
> fix comments belonging to users

- controllers/moviesController.js
- models/movie.js
- package-lock.json
- package.json
- public/js/main.js
- public/stylesheets/style.css
- routes/movies.js
- utils/timeConverter.js
- views/movies/show.ejs
- views/users/show.ejs
comments layout and timestamp still working on it
> Comment styling and timestamp

- views/movies/recs.ejs
> we're showing something on the recs page, just too much!

- controllers/moviesController.js
- public/stylesheets/style.css
- routes/movies.js
- utils/timeConverter.js
- views/movies/recs.ejs
- views/movies/show.ejs
created delete method for comments
> Delete method for comments

- controllers/moviesController.js
> fix movie show time converter

- views/movies/show.ejs
add buy ticket link to fandango
> add buy ticket link to fandango

- controllers/apiController.js
- routes/api.js
- server.js
api ranking movies more to follow
> api ranking

- controllers/moviesController.js
- views/movies/index.ejs
Add 2nd api hit to index page: upcoming
> Add 2nd api hit to index page: upcoming

- controllers/apiController.js
- routes/api.js
> api routes

- controllers/moviesController.js
- views/movies/show.ejs
> Add details on movie show

- controllers/apiController.js
- readme.md
- routes/api.js
> readme final version

- config/passport.js
- controllers/moviesController.js
- controllers/usersController.js
- models/user.js
- public/js/main.js
- routes/index.js
- routes/users.js
- views/_partials/header.ejs
- views/movies/index.ejs
- views/users/show.ejs
cleaned up dead code and indented stuff.
> Clean and indented code
